# Generated by Django 5.0.6 on 2024-05-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='Default description', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='Descripcion Temporal', upload_to='portfolio/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='Descripcion Temporal', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
